# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b6ab063292b5de73c7844f2df12313781cde76d8573307ca3b05aa35b8be6eb47ad8f542bc2501e078ba233504d359024dc4b3155a68282c5e18c9371c2b1ca

test:
  secret_key_base: b4a291df9b41f0fa06e126d3f4cf2269329465f100a787bfb4b709f3e606943a40a8b762bca7e23116f7183a1f5abc436dc8fc27fc0480d4d75b4439257d835d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
